---
name: Linting
on:
  pull_request:
  push:
jobs:
  common-tests:
    name: ${{ matrix.tests.name }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tests:
          - name: flake8
          - name: black
          - name: isort
    steps:
      - uses: actions/checkout@v2

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        run: pip3.11 install -r requirements_test.txt

      - name: Run check ${{ matrix.tests.name }}
        run: tox -e ${{ matrix.tests.name }}
