---
name: Unit Tests
on:
  pull_request:
  push:
jobs:
  common-tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        run: pip3.11 install -r requirements_test.txt

      - name: Run 311 check
        run: tox -e 311
