---
name: Unit Tests
on:
  pull_request:
  push:
jobs:
  common-tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        run: pip3.11 install -r requirements_test.txt

      - name: Run 311 check
        run: tox -e 311

      - name: Inject PR number into coverage.xml
        run: sed -i '2i <!-- PR ${{ github.event.number }} -->' coverage.xml

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

      - name: Upload jUnit XML test results
        if: github.event_name == 'push' && github.repository == 'ansible/dvcs-action' && github.ref_name == 'devel'
        continue-on-error: true
        run: >-
          curl -v --user "${{ vars.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_USER }}:${{ secrets.PDE_ORG_RESULTS_UPLOAD_PASSWORD }}"
          --form "xunit_xml=@dvcs-action-test-results.xml"
          --form "component_name=dvcs-action"
          --form "git_commit_sha=${{ github.sha }}"
          --form "git_repository_url=https://github.com/${{ github.repository }}"
          "${{ vars.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL }}/api/results/upload/"
